# Generated by Django 5.0 on 2023-12-26 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=59),
            preserve_default=False,
        ),
    ]
