# Generated by Django 5.0 on 2023-12-28 04:37

import userauth.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_usermanager_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userauth.manager.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
